# Generated by Django 3.2.2 on 2021-08-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user who made transaction'),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='category creator'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner'], name='summary_tra_owner_i_5bea1a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'operation_date'], name='summary_tra_owner_i_843526_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['owner'], name='summary_cat_owner_i_b8426a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('type', 'title', 'owner')},
        ),
    ]
