# Generated by Django 3.2.2 on 2021-08-17 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('summary', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=5, max_digits=26, verbose_name='max sum that user can spend')),
                ('duration', models.DurationField(verbose_name='validity period of widget (in days)')),
                ('criteria', models.CharField(choices=[('M', 'More'), ('L', 'Less')], max_length=1, verbose_name='spending control criteria')),
                ('color', models.CharField(default='ffffffff', max_length=8, verbose_name='color of widget')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date when widget was created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='summary.category', verbose_name='tracked category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user who create widget')),
            ],
            options={
                'verbose_name': 'widget',
                'verbose_name_plural': 'widgets',
                'ordering': ['-creation_date'],
            },
        ),
    ]
